### ISSUE TITLE
undefined method `async_exec' for nil:NilClass

### ISSUE THREAD

**Issue by andersmarkc** [ifad/chronomodel#102]
I keep getting and NoMethodError, you can see the code I use below, as fare I can see is it then using the adapter: chronomodel, the moment I switch to Postgresql as adapter it's running with no problems.

The Yaml I use is one of your examples.
YAML file: https://github.com/ifad/chronomodel/blob/master/spec/config.yml.example

```
require 'sqlite3'
require 'active_record'
require 'chrono_model'
require 'yaml'

#load config file
db_config_file = File.open('database.yml') 
db_config = YAML::load(db_config_file) 


# Connect from Yaml file, need to run the chronomodel
ActiveRecord::Base.establish_connection(db_config)          

class CreateCountry < ActiveRecord::Migration[5.2]
  create_table :countires do |t|                  
    t.string :name  
    t.text :description  
    t.timestamps  
  end
end

```

**Comment by andersmarkc** [comment]
If have now test with active_record version 5.2.4.3 and it works but if i move to a newer version it will not work any more.

**Comment by vjt** [comment]
Hi, thank you for the report.

Could you please post the complete error that you are receiving, so we can reproduce the error?

**Comment by lleirborras** [comment]
Even better, @andersmarkc do you mind writing a spec for the failing case?

**Comment by andersmarkc** [comment]
Here is the full Error @vjt, I will try to write a spec for it as well. 

```
-- create_table(:countires)
Traceback (most recent call last):
	37: from te.rb:17:in `<main>'
	36: from te.rb:18:in `<class:CreateCountry>'
	35: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:619:in `method_missing'
	34: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:879:in `method_missing'
	33: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:858:in `say_with_time'
	32: from /usr/lib/ruby/2.7.0/benchmark.rb:293:in `measure'
	31: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:858:in `block in say_with_time'
	30: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:880:in `block in method_missing'
	29: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:873:in `connection'
	28: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:189:in `connection'
	27: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
	26: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
	25: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
	24: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
	23: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
	22: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
	21: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
	20: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
	19: from /var/lib/gems/2.7.0/gems/chrono_model-1.2.2/lib/active_record/connection_adapters/chronomodel_adapter.rb:25:in `chronomodel_connection'
	18: from /var/lib/gems/2.7.0/gems/chrono_model-1.2.2/lib/active_record/connection_adapters/chronomodel_adapter.rb:25:in `new'
	17: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql_adapter.rb:256:in `initialize'
	16: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql_adapter.rb:771:in `configure_connection'
	15: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:242:in `client_min_messages='
	14: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'
	13: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
	12: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	11: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
	10: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	 9: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	 8: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	 7: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	 6: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	 5: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
	 4: from /var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
	 3: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	 2: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	 1: from /var/lib/gems/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute': undefined method `async_exec' for nil:NilClass (NoMethodError)

```

**Comment by oofdog** [comment]
any update on this? would love to try out this gem on rails 6+

**Comment by tagliala** [comment]
Closing here, feel free to reopen if you s till have issues
