### ISSUE TITLE
error in migrations with ruby 3.0.2 and Rails 6.1.3.2

### ISSUE THREAD

**Issue by amicojeko** [ifad/chronomodel#123]
the migration code is

```ruby
class AddSkipAutomationsToLogframe < ActiveRecord::Migration[6.1]
  def change
    add_column :logframe_logframes, :skip_automations, :boolean, default: false
    add_column :logframe_expectations, :skip_automations, :boolean, default: false
  end
end
```

ad fails with

```
== 20210727121916 AddSkipAutomationsToLogframe: migrating =====================
-- add_column(:logframe_logframes, :skip_automations, :boolean, {:default=>false})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (given 4, expected 3)
/home/jeko/Workspace/orms/db/migrate/20210727121916_add_skip_automations_to_logframe.rb:3:in `change'
/home/jeko/Workspace/orms/bin/rails:9:in `<top (required)>'
/home/jeko/Workspace/orms/bin/spring:15:in `require'
/home/jeko/Workspace/orms/bin/spring:15:in `<top (required)>'

Caused by:
ArgumentError: wrong number of arguments (given 4, expected 3)
/home/jeko/Workspace/orms/db/migrate/20210727121916_add_skip_automations_to_logframe.rb:3:in `change'
/home/jeko/Workspace/orms/bin/rails:9:in `<top (required)>'
/home/jeko/Workspace/orms/bin/spring:15:in `require'
/home/jeko/Workspace/orms/bin/spring:15:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by amicojeko** [comment]
p.s. model logframe has timegate and has no temporal table

**Comment by tagliala** [comment]
It happens when you add parameters to `add_column`, we should confirm that there is a spec trying to

- ✅ `add_column :users, :active, :boolean`
- ❌  `add_column :users, :active, :boolean, default: false`

We should also check for `remove_index` 

Ref: 0d28a6049ee9ebfe6388c1dce471c7f3711bbfee

**Comment by amicojeko** [comment]
try also
`rename_column :logframe_logframes, :skip_automations, :editable_past_values`

`change_column_null :journals, :project_id, true`
