### ISSUE TITLE
Rails edge: Find each broken

### ISSUE THREAD

**Issue by tagliala** [ifad/chronomodel#321]
```
  1) ChronoModel::TimeMachine.find_each 
     Failure/Error: with_hid_pkey { super }
     
     ArgumentError:
       :cursor must include a primary key or other unique column(s)
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation/batches.rb:319:in `ensure_valid_options_for_batching!'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation/batches.rb:261:in `in_batches'
     # ./lib/chrono_model/patches/batches.rb:9:in `block in in_batches'
     # ./lib/chrono_model/time_machine/history_model.rb:37:in `with_hid_pkey'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation/delegation.rb:81:in `block in with_hid_pkey'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation.rb:1359:in `_scoping'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation.rb:541:in `scoping'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation/delegation.rb:81:in `with_hid_pkey'
     # ./lib/chrono_model/patches/batches.rb:9:in `in_batches'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation/batches.rb:171:in `find_in_batches'
     # ~/.rvm/gems/ruby-3.3.4/bundler/gems/rails-9f80efc79119/activerecord/lib/active_record/relation/batches.rb:87:in `find_each'
     # ./spec/chrono_model/time_machine/batches_spec.rb:10:in `each'
     # ./spec/chrono_model/time_machine/batches_spec.rb:10:in `count'
     # ./spec/chrono_model/time_machine/batches_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ~/.rvm/gems/ruby-3.3.4/gems/aruba-2.2.0/lib/aruba/rspec.rb:38:in `block (2 levels) in <top (required)>'
     # ~/.rvm/gems/ruby-3.3.4/gems/aruba-2.2.0/lib/aruba/rspec.rb:25:in `block (2 levels) in <top (required)>'

rspec ./spec/chrono_model/time_machine/batches_spec.rb:10 # ChronoModel::TimeMachine.find_each 
```

**Comment by tagliala** [comment]
rails/rails@bba9cbae2f

rails/rails#52384

**Comment by tagliala** [comment]
Possible workaround, but probably we should also override `find_in_batches` and `find_each`

```diff
diff --git a/lib/chrono_model/patches/batches.rb b/lib/chrono_model/patches/batches.rb
index debacbe..8719816 100644
--- a/lib/chrono_model/patches/batches.rb
+++ b/lib/chrono_model/patches/batches.rb
@@ -3,10 +3,12 @@
 module ChronoModel
   module Patches
     module Batches
-      def in_batches(**)
+      def in_batches(**options)
         return super unless try(:history?)
 
-        with_hid_pkey { super }
+        options[:cursor] = 'hid' if options[:cursor] == 'id'
+
+        with_hid_pkey { super(**options) }
       end
     end
   end
```

The problem would be that you can't pass 'id'
