### ISSUE TITLE
Re-running all database migrations fails every 2nd attempt

### ISSUE THREAD

**Issue by roschaefer** [ifad/chronomodel#56]
When I run
```sh
$ bin/rails db:drop db:create db:migrate
```
multiple times, I get the following error on every 2nd attempt:
```
== 20171103151039 TemporalTables: migrating ===================================
-- extension_enabled?("btree_gist")
   -> 0.0016s
-- enable_extension("btree_gist")
   -> 0.0449s
-- change_table(:impressions, {:temporal=>true, :copy_data=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::WrongObjectType: ERROR:  "impressions" is not a view
HINT:  Use DROP TABLE to remove a table.
: DROP VIEW impressions
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `async_exec'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:73:in `block (2 levels) in execute'
/home/robert/.gem/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/robert/.gem/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/home/robert/.gem/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `block in execute'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/robert/.gem/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:71:in `execute'
/home/robert/.gem/ruby/2.4.0/gems/chrono_model-0.11.1/lib/chrono_model/adapter.rb:883:in `block in chrono_alter'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/home/robert/.gem/ruby/2.4.0/gems/chrono_model-0.11.1/lib/chrono_model/adapter.rb:880:in `chrono_alter'
/home/robert/.gem/ruby/2.4.0/gems/chrono_model-0.11.1/lib/chrono_model/adapter.rb:171:in `block in change_table'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:233:in `transaction'
/home/robert/.gem/ruby/2.4.0/gems/chrono_model-0.11.1/lib/chrono_model/adapter.rb:132:in `change_table'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:600:in `method_missing'
/home/robert/Development/Rails/rundfunk-mitbestimmen/backend/db/migrate/20171103151039_temporal_tables.rb:4:in `up'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:755:in `up'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/robert/.gem/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/robert/.gem/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/robert/.gem/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/robert/.gem/ruby/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/robert/.gem/ruby/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

```

**Comment by vjt** [comment]
This is strange, care to provide please a minimal `schema.rb` to reproduce?

Thanks!

**Comment by roschaefer** [comment]
It's not minimal, but here you go: https://github.com/roschaefer/rundfunk-mitbestimmen/pull/375/

Note that I installed the fork of `Estimize:rake_is` to check if that fixes our build server. Answer: Yes :+1: .

**Comment by roschaefer** [comment]
This issue persists though
